language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master

notifications:
  email: false

git:
  submodules: false
  
addons:
  apt:
    packages:
    - libx11-dev
    - libvulkan-dev
    - g++-5
    - clang-3.6
    - libstdc++-4.8-dev
    
before_install:
  - if [ "$CXX" = "g++" ]; then
      export CXX="g++-5" CC="gcc-5";
    fi

before_script:
  - cmake -DTARGET_LINUX=ON .

script:
  - make -j 4
